name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
      working-directory: functions/
    - run: npm run lint
      working-directory: functions/
      
